In [1]:
import pandas as pd

In [6]:
ticker_15 = pd.read_csv('./all_prices_15.csv', index_col= 'Date')
ticker_15.index = pd.to_datetime(ticker_15.index)
ticker_15

,AAPL,AMZN,NVDA,JPM,PG,PFE,JNJ,KO,XOM,NEE,GOOGL,MSFT,TSLA,NKE,BAC
Date,,,,,,,,,,,,,,,
2018-04-30,43.635254,79.047501,59.177723,92.023247,62.691250,26.604635,107.132866,35.616982,57.760536,36.229115,52.549999,89.424377,19.606001,64.398087,25.773750
2018-05-07,44.765125,80.145500,63.007214,96.631638,63.504879,27.108622,109.763962,35.431995,61.050396,35.489479,55.168999,91.811287,20.070667,64.710152,27.198784
2018-05-14,44.394451,78.718498,60.880829,94.314720,63.574104,27.481207,107.176018,35.465626,61.684383,34.542301,53.481998,90.552055,18.454666,67.443069,26.618214
2018-05-21,44.935356,80.507500,61.707607,93.915833,64.318474,27.512045,104.786446,35.650600,59.719284,35.860397,54.203999,92.832115,18.590000,68.322510,26.530241
2018-05-28,45.330898,82.077003,63.811558,91.997810,63.574104,27.951559,105.381111,36.255989,62.086517,36.006126,56.750000,95.125565,19.454666,68.804787,25.861712
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-03-27,164.233780,103.290001,277.718353,127.472801,145.918686,39.387459,152.730377,61.076588,106.855545,76.061516,103.730003,287.063324,207.460007,121.829010,28.139095
2023-04-03,163.994766,102.059998,270.319733,124.694626,149.382904,40.063225,162.731750,61.874138,112.107712,77.926544,108.419998,290.349182,185.059998,119.425018,27.391342
2023-04-10,164.542542,102.510002,267.530273,136.774521,148.185623,39.763954,163.411652,62.080910,113.082138,76.989098,108.870003,284.912659,185.000000,125.117119,29.044270
2023-04-17,164.353302,106.959999,271.139587,138.559006,153.161148,38.817883,160.307785,63.065544,113.043159,77.946274,105.410004,284.534271,165.080002,124.699898,29.388628
2023-04-24,168.994461,105.449997,277.438416,136.291428,154.426193,37.543587,161.302994,63.164001,115.313568,75.617455,107.339996,305.942047,164.309998,125.882027,28.808138

In [7]:
## 공분산행렬
cov_matrix = ticker_15.cov()
cov_matrix

,AAPL,AMZN,NVDA,JPM,PG,PFE,JNJ,KO,XOM,NEE,GOOGL,MSFT,TSLA,NKE,BAC
AAPL,2109.154696,1057.755199,3270.069706,767.889501,1044.487197,255.222557,866.578451,296.801354,404.862455,692.488486,1245.136903,3222.386778,4931.164231,1087.238507,221.155242
AMZN,1057.755199,1140.170543,1715.578648,432.560609,504.741861,73.234457,376.631184,73.693454,-231.998129,363.479757,762.978477,1804.353894,2915.887562,810.258108,123.039475
NVDA,3270.069706,1715.578648,5923.926829,1353.985056,1573.130733,420.421285,1271.752345,435.984945,628.686725,1029.212680,2111.462587,5241.208874,7840.613208,1884.164216,390.020769
JPM,767.889501,432.560609,1353.985056,511.742212,385.333323,96.774378,328.890831,114.825962,157.881433,260.810103,570.424086,1285.304674,1910.289321,544.154148,139.476906
PG,1044.487197,504.741861,1573.130733,385.333323,615.595328,128.465205,446.621702,169.185295,183.309933,370.996558,602.063382,1654.071144,2323.170815,558.307319,105.989132
PFE,255.222557,73.234457,420.421285,96.774378,128.465205,52.586512,121.857008,45.679872,99.978835,81.373484,162.684496,388.616238,619.578797,114.499165,34.358545
JNJ,866.578451,376.631184,1271.752345,328.890831,446.621702,121.857008,413.486054,137.950106,221.494622,293.209503,514.361001,1326.260398,1996.744381,426.555636,95.557355
KO,296.801354,73.693454,435.984945,114.825962,169.185295,45.679872,137.950106,59.887629,112.691809,101.881963,166.305292,446.873559,635.394875,128.049528,33.336403
XOM,404.862455,-231.998129,628.686725,157.881433,183.309933,99.978835,221.494622,112.691809,467.808483,109.045155,172.588380,482.903300,681.101667,23.814958,50.911529
NEE,692.488486,363.479757,1029.212680,260.810103,370.996558,81.373484,293.209503,101.881963,109.045155,252.043168,406.106852,1085.378171,1614.537776,375.349396,70.968311
GOOGL,1245.136903,762.978477,2111.462587,570.424086,602.063382,162.684496,514.361001,166.305292,172.588380,406.106852,886.152143,2046.840322,3181.448008,763.253579,173.222610
MSFT,3222.386778,1804.353894,5241.208874,1285.304674,1654.071144,388.616238,1326.260398,446.873559,482.903300,1085.378171,2046.840322,5209.439395,7696.553231,1826.710659,366.866789
TSLA,4931.164231,2915.887562,7840.613208,1910.289321,2323.170815,619.578797,1996.744381,635.394875,681.101667,1614.537776,3181.448008,7696.553231,13063.675581,2765.128479,591.496656
NKE,1087.238507,810.258108,1884.164216,544.154148,558.307319,114.499165,426.555636,128.049528,23.814958,375.349396,763.253579,1826.710659,2765.128479,811.989691,145.773168
BAC,221.155242,123.039475,390.020769,139.476906,105.989132,34.358545,95.557355,33.336403,50.911529,70.968311,173.222610,366.866789,591.496656,145.773168,44.257108

In [8]:
# 가중치 제약
n_assets = cov_matrix.shape[0]
min_weight = (1/2) * (1/n_assets)
max_weight = 2 * (1/n_assets)

In [10]:
# 15 종목에 대해 opt
import numpy as np
from scipy.optimize import minimize

# 목적함수
def portfolio_variance(weights, cov_matrix):
    return np.dot(weights.T, np.dot(cov_matrix, weights))

# 상관관계 축소를 위한 λ 값 설정 (예시로 0.75를 사용)
lambda_shrinkage = 0.75

# 대칭 행렬로 조정
cov_matrix_np = cov_matrix.to_numpy()
cov_matrix_symmetric = (cov_matrix_np + cov_matrix_np.T) / 2

# 상관관계 행렬 조정
corr_matrix = ticker_15.corr()  # 상관관계 행렬 계산
identity_matrix = np.eye(corr_matrix.shape[0])
adjusted_corr_matrix = (1 - lambda_shrinkage) * corr_matrix + lambda_shrinkage * identity_matrix

# 각 자산의 변동성 계산
volatilities = np.sqrt(np.diag(cov_matrix_symmetric))

# 분산-공분산 행렬 재계산
cov_matrix_psd = np.outer(volatilities, volatilities) * adjusted_corr_matrix

# 제약조건
constraints = ({'type': 'eq', 'fun': lambda x: np.sum(x) - 1})
bounds = [(min_weight, max_weight) for _ in range(n_assets)]

# 초기 추정치
initial_guess = [1/n_assets] * n_assets

# 최적화
result = minimize(portfolio_variance, initial_guess, args=(cov_matrix_psd,), method='SLSQP', bounds=bounds, constraints=constraints)

# 종목수 컬럼
ticker_symbols = cov_matrix.columns

# 최적 가중치
optimal_weights = result.x
optimal_weight_dict_15 = {ticker: weight for ticker, weight in zip(ticker_symbols, optimal_weights)}

In [11]:
optimal_weight_dict_15

{'AAPL': 0.03333333333333333,
 'AMZN': 0.03333333333333333,
 'NVDA': 0.033333333731323904,
 'JPM': 0.03333333333333333,
 'PG': 0.03333333333333333,
 'PFE': 0.13333333333333333,
 'JNJ': 0.03333333333333333,
 'KO': 0.13333333333333333,
 'XOM': 0.13333333333333333,
 'NEE': 0.13333333333333333,
 'GOOGL': 0.03333333333333333,
 'MSFT': 0.03333333364474891,
 'TSLA': 0.03333333412625422,
 'NKE': 0.03333333333333333,
 'BAC': 0.13333333333333333}

In [12]:
# 딕셔너리를 데이터 프레임으로 변환
ticker_15_optimal_weights = pd.DataFrame(list(optimal_weight_dict_15.items()), columns=['Ticker', 'Weight'])
ticker_15_optimal_weights.to_csv('./ticker_15_EPO_optimal_weights.csv', index=False)

In [13]:
ticker_15_optimal_weights

   Ticker    Weight
0    AAPL  0.033333
1    AMZN  0.033333
2    NVDA  0.033333
3     JPM  0.033333
4      PG  0.033333
5     PFE  0.133333
6     JNJ  0.033333
7      KO  0.133333
8     XOM  0.133333
9     NEE  0.133333
10  GOOGL  0.033333
11   MSFT  0.033333
12   TSLA  0.033333
13    NKE  0.033333
14    BAC  0.133333